// Load spectrum cards (simplified version of cards from original)
// In production, these would be loaded from JSON files with i18n support

export const dutchSpectrumCards = [
  // Basic cards - gameplay fundamentals
  ["Slechte acteur", "Goede acteur"],
  ["Eenvoudig", "Hipster"],
  ["Waardeloos", "Onbetaalbaar"],
  ["Natuur", "Opgroeien"],
  ["Gebeurt langzaam", "Gebeurt plotseling"],
  ["Baan", "Carrière"],
  ["Rond", "Spits"],
  ["Bewijs dat een hoger wezen bestaat", "Bewijs dat een hoger wezen niet bestaat"],
  ["Geliefd", "Gehaat"],
  ["De 'light side of the Force'", "De 'dark side of the Force'"],
  ["Dom", "Briljant"],
  ["Ambachtelijk", "Massaproductie"],
  ["Niemand doet het", "Iedereen doet het"],
  ["Kortstondig", "Langdurig"],
  ["Gevaarlijke baan", "Veilige baan"],
  ["Fantasie", "Sci-Fi"],
  ["Gewoon", "Fancy"],
  ["Heeft een slechte reputatie", "Heeft een goede reputatie"],
  ["Ethisch om te eten", "Onethisch om te eten"],
  ["Niet modieus", "Modieus"],
  ["Vrijheidsstrijder", "Terrorist"],
  ["Slechte superkracht", "Goede superkracht"],
  ["Ineffectief", "Effectief"],
  ["Beter heet", "Beter koud"],
  ["Vierkant", "Rond"],
  ["Tijdelijk", "Permanent"],
  ["Ziet eruit als een persoon", "Ziet er niet uit als een persoon"],
  ["Niet cool", "Cool"],
  ["Slechtste levende persoon", "Grootste levende persoon"],
  ["Onderschat", "Overschat"],
  ["Romantisch eten", "Nette eten"],
  ["Onvergeeflijk", "Vergeeflijk"],
  ["Falen", "Meesterstuk"],
  ["Ongevaarlijk", "Schadelijk"],
  ["Griffioen", "Zwadderich"],
  ["Onhygienisch", "Hygiënisch"],
  ["Slechte muziek", "Goede muziek"],
  ["Nutteloos", "Nuttig"],
  ["Onbelangrijk", "Belangrijk"],
  ["Makkelijk te spellen", "Moeilijk te spellen"],
  ["Gebrek", "Deugd"],
  ["Onpopulaire activiteit", "Populaire activiteit"],
  ["Gescheiden", "Geheel"],
  ["Onbetrouwbaar", "Betrouwbaar"],
  ["Makkelijk te doden", "Moeilijk te doden"],
  ["Onstabiel", "Stabiel"],
  ["Zwak", "Sterk"],
  ["Slecht", "Goed"],
  ["Schurk", "Held"],
  ["Saaie", "Spannend"],
  ["Onpopulair", "Populair"],
  ["Vriend", "Vijand"],
  ["Liberaal", "Conservatief"],
  ["Heet", "Koud"],
  ["Normaal", "Raar"],
  ["Kleurloos", "Kleurrijk"],
  ["Lage calorie", "Hoge calorie"],
  ["Makkelijk onderwerp", "Moeilijk onderwerp"],
  ["Onbekend", "Beroemd"],
  ["Zeldzaam", "Gewoon"],
  ["Goedkoop", "Duur"],
  ["Voelt slecht", "Voelt goed"],
  ["Onbelangrijk", "Belangrijk"],
  ["Vies", "Schoon"],
  ["Vereist veel geluk", "Vereist goede vaardigheden"],
  ["Smaakloos", "Smaakvol"],
  ["Saai onderwerp", "Fascinerend onderwerp"],
  ["Informeel", "Formeel"],
  ["Onderbetaald", "Overbetaald"],
  ["Droog", "Nat"],
  ["Verboden", "Aangemoedigd"],
  ["Triest lied", "Blij lied"],
  ["Breekbaar", "Duurzaam"],
  ["Goed", "Kwaad"],
  ["Slechtste dag van het jaar", "Beste dag van het jaar"],
  ["Slechte gewoonte", "Goede gewoonte"],
  ["Kattenmens", "Hondenmens"],
  ["Moeilijk te doen", "Makkelijk te doen"],
  ["Mentale activiteit", "Fysieke activiteit"],
  ["Moeilijk te vinden", "Makkelijk te vinden"],
  ["Moeilijk te onthouden", "Makkelijk te onthouden"],
  ["Ongezond", "Gezond"],
  ["Lelijk", "Mooi"],
  ["Gewoon", "Buitengewoon"],
  ["Moeilijk uit te spreken", "Makkelijk uit te spreken"],
  ["Slecht gemaakt", "Goed gemaakt"],
  ["Geen sandwich", "Een sandwich"],
  ["Gevaarlijk", "Veilig"],
  ["Optioneel", "Verplicht"],
  ["Lage kwaliteit", "Hoge kwaliteit"],
  ["Stille plaats", "Luide plaats"],
  ["Komedie", "Drama"],
  ["Noodzaak", "Willen"],
  ["Droog voedsel", "Nat voedsel"],
  ["Vervangbaar", "Onvervangbaar"],
  ["Slechtste atleet ooit", "Grootste atleet aller tijden"],
  ["Saaie hobby", "Interessante hobby"],
  ["Slechte pizzatopping", "Goede pizzatopping"],
  ["Dystopia", "Utopia"],
  ["Ruw", "Glad"],
  ["Slecht voor je", "Goed voor je"],
  ["Vreedzaam", "Krijgshaftig"],
  ["Smaakt slecht", "Smaakt goed"],
  ["Sport", "Spel"],
  ["Trieste film", "Blije film"],
  ["Tijdverspilling", "Goed gebruik van tijd"],
  ["Snack", "Maaltijd"],
  ["Ongelooflijk", "Geloofwaardig"],
  ["Mode", "Klassiek"],
  ["Ruikt slecht", "Ruikt goed"],
  ["Star Wars", "Star Trek"],
  ["Angstaanjagend dier", "Aardig dier"],
  ["Mainstream", "Niche"],
  ["Donker", "Licht"],
  ["Moeilijk te gebruiken", "Makkelijk te gebruiken"],
  ["Vermoeiend", "Energiserend"],
  ["Slecht persoon", "Goed persoon"],
  ["Zacht", "Hard"],
  ["Recht", "Rond"],
  ["Gemene persoon", "Leuke persoon"]
];

// Get a random spectrum card
export function getRandomCard() {
  const index = Math.floor(Math.random() * dutchSpectrumCards.length);
  return dutchSpectrumCards[index];
}

// Get card by index (for deterministic selection)
export function getCardByIndex(index) {
  return dutchSpectrumCards[index % dutchSpectrumCards.length];
}
